// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Tour.Infrastructure.Persistence.SqlServer.Migrations
{
    [DbContext(typeof(TourDbContext))]
    partial class TourDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Category", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<bool>("active")
                        .HasColumnType("bit");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("image_public_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("bit");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("sequence")
                        .HasColumnType("int");

                    b.Property<string>("updated_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("updated_date")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("Categories", (string)null);

                    b.HasData(
                        new
                        {
                            id = 1,
                            active = false,
                            created_by = "",
                            is_deleted = false,
                            name = "Tour Miền Trung",
                            updated_by = ""
                        },
                        new
                        {
                            id = 2,
                            active = false,
                            created_by = "",
                            is_deleted = false,
                            name = "Tour Miền Bắc",
                            updated_by = ""
                        });
                });

            modelBuilder.Entity("Domain.Entities.Departure", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<decimal>("adult_price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("child_price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("current_participants")
                        .HasColumnType("int");

                    b.Property<DateTime>("end_date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("infant_price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("bit");

                    b.Property<int>("max_participants")
                        .HasColumnType("int");

                    b.Property<DateTime>("start_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<int>("travel_tour_id")
                        .HasColumnType("int");

                    b.Property<string>("updated_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("updated_date")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.HasIndex("travel_tour_id");

                    b.ToTable("Departures", (string)null);

                    b.HasData(
                        new
                        {
                            id = 1,
                            adult_price = 5200000m,
                            child_price = 3900000m,
                            created_by = "",
                            current_participants = 5,
                            end_date = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            infant_price = 1000000m,
                            is_deleted = false,
                            max_participants = 20,
                            start_date = new DateTime(2026, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            status = 1,
                            travel_tour_id = 1,
                            updated_by = ""
                        },
                        new
                        {
                            id = 2,
                            adult_price = 4500000m,
                            child_price = 3300000m,
                            created_by = "",
                            current_participants = 30,
                            end_date = new DateTime(2026, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            infant_price = 500000m,
                            is_deleted = false,
                            max_participants = 30,
                            start_date = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            status = 3,
                            travel_tour_id = 2,
                            updated_by = ""
                        });
                });

            modelBuilder.Entity("Domain.Entities.Image", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("bit");

                    b.Property<bool>("is_primary")
                        .HasColumnType("bit");

                    b.Property<string>("public_id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("travel_tour_id")
                        .HasColumnType("int");

                    b.Property<string>("updated_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("updated_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("id");

                    b.HasIndex("travel_tour_id");

                    b.ToTable("Images", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Schedule", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("day_number")
                        .HasColumnType("int");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("bit");

                    b.Property<string>("meal_of_the_day")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("travel_tour_id")
                        .HasColumnType("int");

                    b.Property<string>("updated_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("updated_date")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.HasIndex("travel_tour_id");

                    b.ToTable("Schedules", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.TravelTour", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<bool>("active")
                        .HasColumnType("bit");

                    b.Property<decimal>("base_price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("cancel_policy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("category_id")
                        .HasColumnType("int");

                    b.Property<string>("code_tour")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("excludes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("includes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("bit");

                    b.Property<bool>("is_preferred")
                        .HasColumnType("bit");

                    b.Property<string>("location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("operator_id")
                        .HasColumnType("int");

                    b.Property<string>("terms_and_conditions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("total_days")
                        .HasColumnType("int");

                    b.Property<int>("total_nights")
                        .HasColumnType("int");

                    b.Property<string>("updated_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("updated_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("vehicle_description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("id");

                    b.HasIndex("category_id");

                    b.ToTable("TravelTours", (string)null);

                    b.HasData(
                        new
                        {
                            id = 1,
                            active = false,
                            base_price = 5000000m,
                            cancel_policy = "Hủy trước 7 ngày không mất phí",
                            category_id = 1,
                            code_tour = "DNA001",
                            created_at = new DateTime(2026, 4, 27, 4, 5, 51, 423, DateTimeKind.Utc).AddTicks(9450),
                            created_by = "",
                            description = "",
                            excludes = "Vé máy bay, Chi phí cá nhân",
                            includes = "Khách sạn 3 sao, Ăn sáng, Vé tham quan",
                            is_deleted = false,
                            is_preferred = false,
                            location = "Đà Nẵng",
                            operator_id = 0,
                            terms_and_conditions = "Áp dụng cho đoàn từ 10 người",
                            title = "Tour Đà Nẵng - Hội An",
                            total_days = 3,
                            total_nights = 2,
                            updated_by = "",
                            vehicle_description = "Xe du lịch đời mới 45 chỗ"
                        },
                        new
                        {
                            id = 2,
                            active = false,
                            base_price = 4500000m,
                            cancel_policy = "Hủy sau 3 ngày mất 50% phí",
                            category_id = 2,
                            code_tour = "SAP002",
                            created_at = new DateTime(2026, 4, 27, 4, 5, 51, 424, DateTimeKind.Utc).AddTicks(590),
                            created_by = "",
                            description = "",
                            excludes = "Đồ uống trong bữa ăn",
                            includes = "Vé cáp treo, Khách sạn, Hướng dẫn viên",
                            is_deleted = false,
                            is_preferred = false,
                            location = "Lào Cai",
                            operator_id = 0,
                            terms_and_conditions = "Trẻ em cần có CMND/Khai sinh",
                            title = "Khám phá Fansipan Sapa",
                            total_days = 2,
                            total_nights = 1,
                            updated_by = "",
                            vehicle_description = "Xe giường nằm chất lượng cao"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Vehicle", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("capacity")
                        .HasColumnType("int");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("current_odometer")
                        .HasColumnType("int");

                    b.Property<string>("driver_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("driver_phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("bit");

                    b.Property<string>("license_plate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<string>("updated_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("updated_date")
                        .HasColumnType("datetime2");

                    b.HasKey("id");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            id = 1,
                            capacity = 16,
                            created_by = "",
                            current_odometer = 15000,
                            driver_name = "Nguyễn Văn A",
                            driver_phone = "0901234567",
                            is_deleted = false,
                            license_plate = "29A-111.11",
                            name = "Ford Transit Luxury",
                            status = 1,
                            updated_by = ""
                        },
                        new
                        {
                            id = 2,
                            capacity = 45,
                            created_by = "",
                            current_odometer = 50000,
                            driver_name = "Trần Văn B",
                            driver_phone = "0907654321",
                            is_deleted = false,
                            license_plate = "29B-222.22",
                            name = "Hyundai Universe",
                            status = 1,
                            updated_by = ""
                        });
                });

            modelBuilder.Entity("Domain.Entities.VehicleAssignment", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("Scheduleid")
                        .HasColumnType("int");

                    b.Property<DateTime>("assigned_at")
                        .HasColumnType("datetime2");

                    b.Property<string>("created_by")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("created_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("departure_id")
                        .HasColumnType("int");

                    b.Property<int?>("departureid")
                        .HasColumnType("int");

                    b.Property<DateTime>("from_date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("is_deleted")
                        .HasColumnType("bit");

                    b.Property<string>("note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("to_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("updated_by")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("updated_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("vehicle_id")
                        .HasColumnType("int");

                    b.Property<int?>("vehicleid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("Scheduleid");

                    b.HasIndex("departureid");

                    b.HasIndex("vehicleid");

                    b.ToTable("VehicleAssignments");

                    b.HasData(
                        new
                        {
                            id = 1,
                            assigned_at = new DateTime(2026, 4, 27, 4, 5, 51, 423, DateTimeKind.Utc).AddTicks(8200),
                            created_by = "",
                            departure_id = 1,
                            from_date = new DateTime(2026, 4, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            is_deleted = false,
                            note = "Đón tại KS Mường Thanh",
                            to_date = new DateTime(2026, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            updated_by = "",
                            vehicle_id = 1
                        });
                });

            modelBuilder.Entity("Domain.Entities.Departure", b =>
                {
                    b.HasOne("Domain.Entities.TravelTour", "travel_tour")
                        .WithMany("departures")
                        .HasForeignKey("travel_tour_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("travel_tour");
                });

            modelBuilder.Entity("Domain.Entities.Image", b =>
                {
                    b.HasOne("Domain.Entities.TravelTour", "travel_tour")
                        .WithMany("images")
                        .HasForeignKey("travel_tour_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("travel_tour");
                });

            modelBuilder.Entity("Domain.Entities.Schedule", b =>
                {
                    b.HasOne("Domain.Entities.TravelTour", "travel_tour")
                        .WithMany("schedules")
                        .HasForeignKey("travel_tour_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("travel_tour");
                });

            modelBuilder.Entity("Domain.Entities.TravelTour", b =>
                {
                    b.HasOne("Domain.Entities.Category", "category")
                        .WithMany("travel_tours")
                        .HasForeignKey("category_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("category");
                });

            modelBuilder.Entity("Domain.Entities.VehicleAssignment", b =>
                {
                    b.HasOne("Domain.Entities.Schedule", null)
                        .WithMany("vehicle_assignments")
                        .HasForeignKey("Scheduleid");

                    b.HasOne("Domain.Entities.Departure", "departure")
                        .WithMany("vehicle_assignments")
                        .HasForeignKey("departureid");

                    b.HasOne("Domain.Entities.Vehicle", "vehicle")
                        .WithMany("assignments")
                        .HasForeignKey("vehicleid");

                    b.Navigation("departure");

                    b.Navigation("vehicle");
                });

            modelBuilder.Entity("Domain.Entities.Category", b =>
                {
                    b.Navigation("travel_tours");
                });

            modelBuilder.Entity("Domain.Entities.Departure", b =>
                {
                    b.Navigation("vehicle_assignments");
                });

            modelBuilder.Entity("Domain.Entities.Schedule", b =>
                {
                    b.Navigation("vehicle_assignments");
                });

            modelBuilder.Entity("Domain.Entities.TravelTour", b =>
                {
                    b.Navigation("departures");

                    b.Navigation("images");

                    b.Navigation("schedules");
                });

            modelBuilder.Entity("Domain.Entities.Vehicle", b =>
                {
                    b.Navigation("assignments");
                });
#pragma warning restore 612, 618
        }
    }
}
